spring:
   h2:
      console:
         enabled: true
   datasource:
      url: jdbc:h2:mem:testdb
   jpa:
      show-sql: true
   main:
      banner-mode: off

logging:
   level:
      root: info
      com.profounddistortion: debug
   pattern:
      console: "%d %magenta([%-7.7thread]) %highlight(%-5level) %-40.40logger{0} : %msg%n"

jwt:
   expire:
      millis: 36000000 # 10 hours for now
